source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '15.0'
use_frameworks!

target 'imageSearch' do
    pod 'Alamofire', '~> 5.4'
    pod 'Kingfisher', '~> 7.0'
    pod 'SnapKit', '~> 5.0.0'
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
end